# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('translate_date', models.DateTimeField(verbose_name='date translated')),
                ('detected_langugae_code', models.CharField(max_length=10)),
                ('detected_language', models.CharField(max_length=100)),
            ],
        ),
    ]
